### ISSUE TITLE
Error on module

### ISSUE THREAD

**Issue by rafaelvelosoAZ** [bridgecrewio/terraform-azurerm-bridgecrew-azure-read-only#5]
We are getting this error:
Error: Unsupported attribute
│ 
│   on .terraform/modules/bridgecrew-read/main.tf line 22, in locals:
│   22:     oauth2_permissions = { for p in data.azuread_service_principal.graph.oauth2_permissions : p.value => p.id }
│ 
│ This object has no argument, nested block, or exported attribute named "oauth2_permissions".

**Comment by JamesWoolfenden** [comment]
fix pushed
