### ISSUE TITLE
URL using bad/illegal format or missing URL

### ISSUE THREAD

**Issue by j4t1nd3r** [bridgecrewio/terraform-azurerm-bridgecrew-azure-read-only#7]
Steps taken:
1) Named token, from the bridgecrew portal, copied module "bridgecrew-read" to main tf.
2) installed curl, confirmed its available in terminal via curl --help
3) terraform init
4) terraform apply -auto-approve 

System details:
TF version: 1.1.7
OS: WIn 11

Error in terminal:

Error: local-exec provisioner error
│
│   with module.bridgecrew-read.null_resource.notify_bridgecrew,
│   on .terraform\modules\bridgecrew-read\null_resource.notify_bridgecrew.tf line 8, in resource "null_resource" "notify_bridgecrew":
│    8:   provisioner "local-exec" {
│
│ Error running command '      curl --request PUT 'https://www.bridgecrew.cloud/api/v1/integrations/csp' \
│       --header 'Authorization: 'REMOVED' \
│       --header 'Content-Type: application/json' \
│       --data-raw '{REMOVED}'
│ ': exit status 6. Output: curl: (3) URL using bad/illegal format or missing URL
│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
│                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: \

**Comment by JamesWoolfenden** [comment]
This module isnt tested at all on windows, if there's a strong requirement for it to work on Windows let me know.

**Comment by j4t1nd3r** [comment]
no longer relevant, closing.
